### PR TITLE
Don't show room title in admin room list

### PR DESCRIPTION
**Pull request by mas90**
We do not need to know what users are using Timeout for.

### CODE REVIEW

**Comment by matiasilva** [comment]
Few concerns:

* We say that Timeout is for personal + uni business. How can we tell someone is not using Timeout to do otherwise?
* What if someone changes their title to something obscene? Or leaks credentials, other serious data in the title and invites users to the room?
* If someone needs us to fix something, it will become much harder to help out as we have to manually query the database. Not a major issue, but worth noting.

In any case, if we do do this, I would much prefer a [redacted] room name than an outright deletion that might mess with future GUI modifications. I agree this would much less "tempt" me into actually looking.

**Comment by mas90** [comment]
> * We say that Timeout is for personal + uni business. How can we tell someone is not using Timeout to do otherwise?
> * What if someone changes their title to something obscene? Or leaks credentials, other serious data in the title and invites users to the room?

Generally the SRCF (in common with many other providers of infrastructure/platforms) does not actively go looking for inappropriate use -- we just act if we are made aware of it.  We can still look at the database if we *need* to.

In any case, someone actively trying to hide inappropriate use from us can just set their room title to "Supervision".

> * If someone needs us to fix something, it will become much harder to help out as we have to manually query the database. Not a major issue, but worth noting.

Can you come up with a possible scenario?  I don't quite understand what would require us to see the room name without joining the room in order to help.

> In any case, if we do do this, I would much prefer a [redacted] room name than an outright deletion that might mess with future GUI modifications.

Yeah, I did increase the likelihood of future merge woes by moving the start time and the home room icon.  Though I also think putting the start time in the status column makes more sense regardless!

Unsure how much we should sacrifice our own development just to make future merges possibly easier.  Opinions sought!

**Comment by matiasilva** [comment]
Yeah, nothing is impossible it just becomes more difficult. The only idea I had in my mind was if a user wanted a custom URL. 

I'm not sure how the changes to the GUI would look, I'll have to see for myself. As for it making more sense, I'm on the fence about this.

**Comment by mas90** [comment]
> Yeah, nothing is impossible it just becomes more difficult. The only idea I had in my mind was if a user wanted a custom URL.

For which we have to go and prod the database anyway.

Regardless we ought to get users to give us the room URL to uniquely identify the room they're talking about.
 
> As for it making more sense, I'm on the fence about this.

The room start/stop time relates to the "Running" / "Not Running" state, and is unrelated to the room name.  I think upstream just put it in the name column because it fit the layout, not because it actually belonged under that column heading.

**Pull request merged**
